### PR TITLE
Updated Security Example in Readme

### PR DESCRIPTION
**Pull request by Austio**
Wanted to expand on this explicitly so that users of the gem that are newer to rails understand their options for securing the controller.

### CODE REVIEW

**Comment by Nedomas** [comment]
Thank you, Austin :heart: :heart: :heart: 

I will eventually merge this along with putting this on databound.me and pushing out a build that allows for a better Rails side API.

What I have half-done right now is this:

``` ruby
class UsersController < ApplicationController
  databound do
    model :user
    columns :name, :city, :user_id

    permit(:create, :destroy) do |params|
      params.user_id == current_user.id
    end

    # or
    permit(:destroy) do |params|
      authorize!(:destroy, params)
    end
  end
end
```

I think this is a bit clearer API for doing that and having no calls to `super` then.

What are your thoughts on that?

**Comment by Austio** [comment]
I like it, much more clear, are you needing any help on the branch?  

It makes sense to provide some minimal authorization so that people can just get it up and running quickly.  I think that anything past the minimal authorization should be handled by separate concern(pundit, cancancan, etc).  Then you are able to keep databound focused on the really awesome things that it does (which i am incredibly excited about BTW)

**Comment by Nedomas** [comment]
It is almost done. Just need to update the tests and some other quirks. Its at https://github.com/Nedomas/databound-rails/tree/simpler_configuration

I'm also thinking about checking out the performance benchmarks for both `databound` js lib and `databound-rails` and optimizing up them. Have you ever tried something like `benchmark-ips` ?

**Comment by Nedomas** [comment]
This new syntax was released with v3.0.1 of Databound https://github.com/Nedomas/databound-rails/commit/30e340d2027fb7b0a040a30ef1788b93ecbf14e1

I've also updated the docs and the website to include your suggestions on 3rd party libraries. https://github.com/Nedomas/databound-website/commit/6661ead66e6748556ab1f0801994920ee42d9cd1

Thank you again :heart:  :heart:  :heart:

**Pull request closed without merging**
